# Usea a Python base image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the file requirements.txt
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

# Copy the application code
COPY . .

Sets the environment variable for Flask
ENV FLASK_APP=sayhello

# Create database and generate dummy data
RUN flask forge

# Expose the port
EXPOSE 5000

# Command to run the application
CMD ["flask", "run", "--host=0.0.0.0"]
