# Uses a Node.js base image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json file
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the application code
COPY . .

# Expose the port
EXPOSE 3333

# Command to run the application
CMD ["node", "benchmarks/middleware.js"]
